### ISSUE TITLE
Introduce `getDerivedStateFromProps`

### ISSUE THREAD

**Issue by jpggvilaca** [timhwang21/react-gotchas#3]
Hey man how are you? :) should the `componentWillReceiveProps`, be replaced by the new `getDerivedStateFromProps` ?

**Comment by timhwang21** [comment]
Hey Joao! Yeah that's probably something good to add. Worth noting that the recommended solution is:

1. if you're handling network requests, use `componentDidUpdate()`
2. if you're doing state updates based on props, IF POSSIBLE avoid `getDerivedStateFromProps` and use a cached function that computes values from props as needed
3. only use `getDerivedStateFromProps` if the above is too complex

From [the docs](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops): 

> Deriving state leads to verbose code and makes your components difficult to think about.
Make sure you’re familiar with simpler alternatives:
